### ISSUE TITLE
Broken transition from 0.17 container to new one

### ISSUE THREAD

**Issue by yshurik** [dashpay/dash#4947]
I had a problem to update the container to latest version.
I used dashpay/dashd:0.17.0.0-rc3-hotfix1 (installed while ago)
Now it does not sync anymore - I guess it happened hardfork or something, i did not figure out.
I wanted to upgrade to new container (is it to use 0.18 or latest tag?) 
but looks like it is not possible to run 0.17 anymore but the new container also is not more compatible.

I used next docker-compose:
```
  TDASH:
    image: dashpay/dashd:0.17.0.0-rc3-hotfix1
    restart: unless-stopped
    command: -testnet -printtoconsole -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -rpcauth='xxx:34....34'
    entrypoint: dash_oneshot
    volumes:
      - /mnt/crypto/coins/TDASH:/dash/.dashcore
    ports:
      - "127.0.0.1:12004:19998"
```

New containers do not have dash_oneshot binary anymore looks like.
If I switch to use ```docker-entrypoint.sh``` then it complains about cmd options:

```
/docker-entrypoint.sh: line 21: exec: -t: invalid option
```

How can I upgrade to new container and have same setup? (testnet, rpcbind, rpcauth etc) ?
